# Change these first
owner: VinceHpa # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: Culturatela.com
    url: https://app.culturatela.it
  - name: Cultura Lucca - SUMMÆ
    url: https://cultura.comune.lucca.it
  - name: Servizi di Backend
    url: https://cultura.comune.lucca.it
   - name: Servizi TCK@
    url: https://cultura.comune.lucca.it

status-website:
 
 
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: https://app.culturatela.it
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Attraverso questa pagina puoi monitorare lo stato degli applicativi
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
