# Change these first
owner: VinceHpa # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: Culturatela.com
    url: https://app.culturatela.it
  - name: Cultura Città Lucca SUMMÆ
    url: https://cultura.comune.lucca.it
  - name: Cultura Città Catania 
    url: https://app.culturatela.it
  - name: Cultura Città Ancona
    url: https://app.culturatela.it
  - name: Servizi di Backend
    url: https://app.culturatela.it
  - name: Servizi TCK@
    url: https://biglietteria.culturatela.it

status-website:
 
 
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: https://app.culturatela.it
  baseUrl: /status-page
  logoUrl: https://app.culturatela.it/static/images/Black.png
  name: Cultura Tela - HPA SRL
  introTitle: "Suite Applicativi culturatela.com + white label"
  introMessage: Attraverso questa pagina puoi monitorare lo stato degli applicativi offerti dalla suite
  navbar:
    - title: Status
      href: /status-page
    - title: TELA
      href: https://culturatela.com
    - title: SUMMÆ
      href: https://cultura.comune.lucca.it

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
